Makefile, bower.json, src/scss/form.scss, templates/confirmation.html, templates/marketing-consent.html, templates/overlay.html, templates/yes-no-switch.html
=> Fields can be required or not; styling; use redirect URL for Continue button

src/scss/form.scss, src/scss/typography.scss, templates/marketing-consent.html, templates/yes-no-switch.html
=> Use form of words content to render consent form

dist/client/consent.js, dist/client/live-update.js, dist/client/main.js, dist/client/reconsent.js, dist/client/update-on-save.js, dist/helpers.js, dist/server/main.js, src/js/helpers.ts
I will write tests in the next 2 days, promised.
🐿 v2.8.0
=> throw when no valid consents supplied to build

Makefile, dist/client/consent.js, dist/client/live-update.js, dist/client/main.js, dist/client/reconsent.js, dist/client/update-on-save.js, dist/helpers.js, dist/server/main.js, package.json, src/scss/form.scss, templates/yes-no-switch.html
=> Support optional description & advisory fields for each consent item

bower.json, src/scss/common.scss, src/scss/form.scss, src/scss/layout.scss, src/scss/message.scss, src/scss/typography.scss, templates/changes-saved-message.html, templates/confirmation.html, templates/consent.html, templates/privacy.html, templates/yes-no-switch.html
Addressing [signup form signoff](https://trello.com/c/AwLASMfg/175-update-consent-on-sign-up#comment-5acb7399afaa9fdb41f2d3a1)
and [privacy page](https://trello.com/c/FYfadiRT/98-privacy-settings-page-accessed-from-contact-preferences-page-page-skeleton)
🐿 v2.8.0
=> Add privacy template; typography styles

templates/privacy.html
https://developers.google.com/web/tools/lighthouse/audits/noopener
🐿 v2.8.0
=> Add rel="noopener" to links with _blank target

src/scss/form.scss, src/scss/layout.scss, src/scss/typography.scss, templates/confirmation.html, templates/privacy.html, templates/subheading.html, templates/yes-no-switch.html
Various small changes to improve code reuse - details are in the commit messages.
=> Shared styles

bower.json, dist/client/message.js, src/js/client/message.ts, src/scss/components/alert-message.scss
=> bump o-message

src/scss/layout.scss, src/scss/spacing.scss, src/scss/typography.scss, templates/subheading.html
=> Shared styles moved up from control-centre / renamed more generically

dist/commonjs/client/live-update.js, dist/esm/client/live-update.js, src/js/client/live-update.ts
=> Live update - apply saved class after update

dist/commonjs/helpers.js, dist/esm/helpers.js, src/js/helpers.ts, test/unit/helpers.spec.ts
=> add cookie prefs management helper

dist/commonjs/client/main.js, dist/esm/client/main.js, src/js/client/main.ts, templates/privacy.html
also, if there's an error, don't render submit button in privacy template
=> Expose helpers to client-side code

src/scss/form.scss, src/scss/spacing.scss
=> Form info box padding; extra spacing classes

dist/commonjs/client/message.js, dist/esm/client/message.js, src/js/client/message.ts
=> Fix initialisation and toggling of consent message

src/scss/buttons.scss, src/scss/form.scss, src/scss/spacing.scss, src/scss/subheading.scss, src/scss/typography.scss, templates/confirmation.html, templates/consent.html, templates/settings.html
=> Styles to support manage cookies page

README.md, src/js/helpers.ts
=> Document templates and helpers in readme

bower.json, demos/client/demo.ts, demos/fixtures/fow.json, demos/scss/demo.scss, demos/views/demo-message.html, dist/commonjs/client/live-update.js, dist/commonjs/client/message.js, dist/esm/client/live-update.js, dist/esm/client/message.js, src/js/client/live-update.ts, src/js/client/message.ts, src/scss/buttons.scss, src/scss/common.scss, src/scss/components/alert-message.scss, src/scss/form.scss, src/scss/layout.scss, src/scss/message.scss, src/scss/spacing.scss, src/scss/subheading.scss, src/scss/typography.scss, templates/components/changes-saved-message.html, templates/components/error-message-core.html, templates/components/yes-no-switch.html, templates/confirmation.html, templates/consent.html, templates/settings.html, test/client/live-consent.spec.ts
One breaking test, which we will look into next week. Possibly to do with `[next-test-sessions-lambda](https://github.com/financial-times/next-test-sessions-lambda)`.
=> Origami major cascade

src/scss/form.scss
=> No margin consent form

.gitignore, dist/commonjs/client/consent.js, dist/commonjs/client/live-update.js, dist/commonjs/client/main.js, dist/commonjs/client/message.js, dist/commonjs/client/reconsent.js, dist/commonjs/client/update-on-save.js, dist/commonjs/helpers.js, dist/commonjs/server/main.js, dist/esm/client/consent.js, dist/esm/client/live-update.js, dist/esm/client/main.js, dist/esm/client/message.js, dist/esm/client/reconsent.js, dist/esm/client/update-on-save.js, dist/esm/helpers.js, dist/esm/server/main.js
This package is build as part of a precommit hook, so the distribution
is commited and included in both the npm and bower package.
=> Restore the `dist` directory.

src/scss/form.scss
- Revert accessibiliy changes to terms and conditions whilst we await Product to check with legal regarding copy approval.
[Ticket](https://financialtimes.atlassian.net/browse/AC-112?atlOrigin=eyJpIjoiY2VjZTQ1MzYyMDQ0NDY2MmEwZDYwZjM1ZDFkMjZhM2UiLCJwIjoiaiJ9)
| Before | After |
| ------ | ----- |
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549372-6e4c7c00-4f47-11ea-8844-9255f2ce18c4.png"> | <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549042-d6e72900-4f46-11ea-901a-388508cf43ee.png"> |
=> Revert terms and conditions accessibility changes

bower.json
Jira card: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-84.
The demo uses [n-internal-tool](https://github.com/Financial-Times/n-internal-tool), which wraps the demo HTML with a `.o-grid-container` class, meaning the layout will be slightly different to its current state.
- [`n-ui-foundations` Migration guide v5 to v6](https://github.com/Financial-Times/n-ui-foundations#user-content-v5-to-v6).
=> Upgrade n-ui-foundations 4.0.0-beta.2 -> ^6.0.0

src/scss/form.scss
=> Fix label margin in radio button

src/js/server/components/ConsentLite.tsx
The parent PR of this is [PR](https://github.com/Financial-Times/n-profile-ui/pull/88).
Some comments that have been raised in the PR have been addressed here. 
1. interpolation removal (not needed)
2. check on label and category
=> ACQ-932 Add check on category and label

.circleci/config.yml
Updating the circleCI config yaml to use nodeV12 for build/test
=> Update node version to v12

src/js/server/components/ConsentLite.tsx
Fixing some react warnings on the ConsentFields.CheckBox component
=> Fixing some react warnings on the ConsentFields.CheckBox component

src/js/server/components/ConsentLite.tsx
Add copy for newly registered users to auto-enroll to editor digest newsletter.
https://financialtimes.atlassian.net/browse/ACQ-1382
=> Merge after 18th Jan - Add copy for new reg users enroll to editor digest newsletter

.circleci/config.yml, package-lock.json
[JIRA ticket](https://financialtimes.atlassian.net/jira/software/c/projects/ADSDEV/boards/803?modal=detail&selectedIssue=ADSDEV-1053)
=> [ADSDEV-1053] Ensure npm publish steps use new token

.prettierrc, package-lock.json, package.json, src/js/server/components/Consent.tsx, src/js/server/components/ConsentHeading.tsx, src/js/server/components/ConsentLite.tsx, src/js/server/components/Overlay.tsx, src/scss/form.scss, src/scss/typography.scss
More info: https://financialtimes.atlassian.net/browse/ACQ-1472
It will be used in [User Registration](https://ft.com/register) and Digital buy flows under [FT products](https://www.ft.com/products) for initial A/B testing.
=> ACQ-1472 toggle switch component

src/scss/form.scss
Add margin to the label but not on the last label element.
=> Margin bottom labels inside toggle

.snyk, package.json
In mid-December 2024 we will be letting our Snyk contract expire. We'll
be moving to GitHub Advanced Security as an alternative.
This PR is an attempt to get ahead of the deadline. Considering how out
of date some of our Snyk implementations are, and that we rarely take
the time to merge the PRs, we think it's fine to remove it way ahead of
time.
If you want an interrim solution, enable Dependabot Security updates for
this repository by visiting the following page and clicking 'Enable' next
to 'Dependabot security updates':
https://github.com/Financial-Times/n-profile-ui/settings/security_analysis
You're also free to ignore this PR and do the work yourself closer to
the deadline. Cyber will be doing some broader comms later in the year.
This PR was automated, please take a little extra …
=> Remove snyk [automated]
