.gitignore
demos/app.ts
src/js/client/consent.ts
src/js/client/update-on-save.ts
src/js/helpers.ts
templates/consent.html

Adds a consent source field for core experience and fixes the consent schema (which, erroneously, had `scope` instead of `source`).
🐿 v2.8.0

add consent source field

---

Makefile
README.md
demos/app.ts
dist/client/consent.js
dist/client/live-update.js
dist/client/main.js
dist/client/reconsent.js
dist/client/update-on-save.js
dist/helpers.js
dist/server/main.js
package.json
secret-squirrel.js
src/js/helpers.ts

Adding an `options` interface instead of flat arguments for helper functions – improvement suggested via @remybach's [comment](https://github.com/Financial-Times/next-signup/pull/1400#discussion_r179085188)

add options interface

---

src/scss/buttons.scss
src/scss/form.scss
templates/consent.html

🐿 v2.8.0 Cleans up spacing between the consent-form and the unsub-from-all section on myft-page > emails & alerts
Before:
After:

remove margin-bottom if section is last-child

---

src/scss/buttons.scss

moves submit button spacing becasue css cascades

---

bower.json
dist/client/consent.js
dist/client/live-update.js
dist/client/main.js
dist/client/reconsent.js
dist/client/update-on-save.js
dist/helpers.js
dist/server/main.js
src/scss/form.scss
templates/yes-no-switch.html

🐿 v2.8.0 The latest o-forms release overwrote some consent-form styles. To fix, I've removed some custom code and pulled in the new `__inline` styles from o-forms. 
( So many dist changes 🙈 )
Before:
After:
Total aside, but I found this https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self which we can't use yet (because polyfill?) but Chrome have implemented and omw I want it! 🎉 ❤️

use new o-forms__inline mixins

---

bower.json
src/scss/common.scss
src/scss/subheading.scss
src/scss/typography.scss
templates/subheading.html

Split CSS for 'subheading' component; use external link from o-typography

---

bower.json
templates/yes-no-switch.html

Update to use the new `consent-form--inline-controls` class (Thanks @notlee !)
Before:
Afrer:

Use new inline controls option

---

dist/commonjs/client/live-update.js
dist/commonjs/helpers.js
dist/esm/client/live-update.js
dist/esm/helpers.js
package.json
src/js/client/live-update.ts
src/js/helpers.ts
test/client/helpers/init-consent-form.ts

Fix cookie parser; expect string status from live update callback

---

src/scss/form.scss
src/scss/subheading.scss
templates/subheading.html

Support 3 levels of subheading so the 'thin border' style can have 2 different font sizes
🐿 v2.8.0

Add subheading levels 2 & 3

---

templates/consent.html

The starting h1 was mismatching with the ending h2 and visa versa

Heading tag mismatch

---

src/scss/form.scss

Set the bottom margin between toggles to the o-forms default (20px) and set the bottom margin of a set of toggles to 36px.

Fix spacing between toggles and toggle sections

---

package.json
tsconfig.esm.json

The build currently fails owing to `error TS2304: Cannot find name 'unknown'.` (seen [here](https://circleci.com/gh/Financial-Times/n-profile-ui/1315)).
Fixing this by upgrading from TypeScript v2 -> v3 will then result in `error TS2307: Cannot find module 'vfile-message'` (from `import * as vfileMessage from 'vfile-message';`), which arises because this repo has the following npm dependencies:
`n-profile-ui`
-> `n-gage`
-> `stylelint`
-> `postcss-markdown` (**unmaintained and needs to bump its `remark` dependency v10 -> v11**)
-> `remark`
-> `unified`
-> `vfile`
Requests have been made to the collaborators of the `postcss-markdown` package to release a version with its `remark` dependency upgraded, but only one of them has the required access to npm and they have been absent since the …

Upgrade TypeScript version + specific types to compile

---

src/scss/form.scss

Make consent forms have wider title text because the inputs are all the same width and having a small title section causes the tetx to wrap too much

overwrite o-forms flex for consent-forms

---

bower.json
src/scss/common.scss
src/scss/subheading.scss
templates/subheading.html

This piece of work is required to unblock https://github.com/Financial-Times/next-control-centre in the origami cascade work

remove o-teaser-collection because it is for editorial content and not for product content

---

demos/fixtures/fow.json
src/scss/form.scss

When updating `n-profile-ui` in `next-profile` we lost the background and padding for the consent information displayed above the submit button:
Turns out this was because it wasn't displayed in the demos for `n-profile-ui` and so the styling was removed.
This PR adds that messaging into the demo, and restores that styling.
**Before**
**After**

Restore consent information padding and background

---

dist/commonjs/client/consent.js
dist/commonjs/client/live-update.js
dist/commonjs/client/main.js
dist/commonjs/client/message.js
dist/commonjs/client/reconsent.js
dist/commonjs/client/update-on-save.js
dist/commonjs/helpers.js
dist/commonjs/server/main.js
dist/esm/client/consent.js
dist/esm/client/live-update.js
dist/esm/client/message.js
dist/esm/client/reconsent.js
dist/esm/client/update-on-save.js
dist/esm/helpers.js
dist/esm/server/main.js
src/js/client/live-update.ts
src/scss/form.scss
templates/components/yes-no-switch.html

This fixes up a few things missed or not quite done right from the origami migration.
- Adds some removed styles back in as they were used downstream
- Fixes the error handling code to work
- Uses the label text if passed in for toggle radios
There is also a lot of whitespace changes which were auto generated, not sure what caused that.

Origami fixes

---

templates/components/yes-no-switch.html

In the origami change the labels lost their for attributes as the label
now wraps the input. This ensures that all label tags have a appropriate
for attribute which points at the input they are targeting. Having both
a for attribute and wrapping the input is valid.
This was primarily picked up due to the end to end tests trying to find
the input for a radio button to click.

Add `for` to label tags

---

src/scss/form.scss

- Add margin bottom to consent box to offset new terms and conditions.
[ticket](https://financialtimes.atlassian.net/browse/AC-112?atlOrigin=eyJpIjoiYjJiMzNjYzBmZTQ5NGFmNzkxNWQ3NDEwMDQ5ZDdiYWMiLCJwIjoiaiJ9)
| Before | After |
| -- | -- |
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549042-d6e72900-4f46-11ea-901a-388508cf43ee.png"> | <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549372-6e4c7c00-4f47-11ea-8844-9255f2ce18c4.png"> |

Add margin to bottom of consent box 🐿 v2.12.5

---

src/scss/form.scss

- Add terms and conditions accessibility changes back after removing bullet points from the design.
[Ticket](https://financialtimes.atlassian.net/browse/AC-112?atlOrigin=eyJpIjoiY2VjZTQ1MzYyMDQ0NDY2MmEwZDYwZjM1ZDFkMjZhM2UiLCJwIjoiaiJ9)
| Before | After |
| ------ | ----- |
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549042-d6e72900-4f46-11ea-901a-388508cf43ee.png"> | <img width="728" alt="Screenshot 2020-02-20 at 14 06 44" src="https://user-images.githubusercontent.com/7748470/74960227-da295b80-5403-11ea-96fe-d454e6a6c4bc.png"> |

Revert reverting terms and conditions accessibility changes

---

tsconfig.esm.json

Running `tsc -p tsconfig.commonjs.json` results in:
```
error TS2688: Cannot find type definition file for 'bunyan'.
error TS2688: Cannot find type definition file for 'events'.
error TS2688: Cannot find type definition file for 'restify'.
```
`tsconfig.esm.json`: `compilerOptions.types` are a:
> List of names of type definitions to include. See [@types, –typeRoots and –types](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) for more details.
> If types is specified, only packages listed will be included. For instance:
```
{
"compilerOptions": {
"types" : ["node", "lodash", "express"]
}
}
```
> This `tsconfig.json` file will *only* include `./node_modules/@types/node`, `./node_modules/@types/lodash` and `./node_modules/@types/express`. Other …

Fix unfound type definition file errors

---

CODEOWNERS

This PR specifies the Ads team as owners of this repo.
Follows up the request made by me in https://github.com/Financial-Times/n-profile-ui/pull/76.

Add @Financial-Times/ads team as CODEOWNERS

---

templates/components/yes-no-switch.html

Update `aria-label`  to be configurable as per comments here:
https://github.com/Financial-Times/n-profile-ui/pull/80#discussion_r448267064

NOPS-235 DAC Dragon issue4 second amend

---

src/js/server/components/ConsentLite.tsx
src/js/server/components/index.ts

This is a new Consent Lite component. See the picture below where it is loaded through next-subscribe when referencing this component. 
Any style changes would not be picked up as the frontend assets are pulled by bower and it uses v12 therefore style changes are done on next-subscribe. 
Once this PR is merged, next-subscribe PR with the reference to the new version will be created.

ACQ-932 New Consent Lite component 

---

src/js/server/components/ConsentLite.tsx

There was an `if (category && label)` condition that prevents rendering the fields because it hasn't the `return`. There was two options here, first is to add the `return` sentence or just remove the conditional. I prefer the second because is easier for engineers to detect if the component is receiving wrong values, otherwise is hard to find why the fields are not shown.
https://financialtimes.atlassian.net/browse/ACQ-932
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/13876273/119640210-aa43e180-be18-11eb-939c-ae108c479379.png) | ![image](https://user-images.githubusercontent.com/13876273/119640280-be87de80-be18-11eb-9d26-8c85ae0d3aa1.png) |

ACQ-932: fixing ConsentFields component

---

src/js/server/components/ConsentLite.tsx

In order to add tracking to the consent page on next-subscribe, the submit button of this component needs an additional class name that its used to load the button on client side.
```
submit.js:28 Uncaught (in promise) Error: Please include the submit button partial on the page
at new e (submit.js:28)
at new e (controller.js:48)
at main.js:19
```
https://github.com/Financial-Times/next-subscribe/blob/main/client/controller.js#L48
https://github.com/Financial-Times/n-conversion-forms/blob/main/utils/submit.js#L25-L29
https://financialtimes.atlassian.net/browse/ACQ-922

ACQ-922: Adding missing class name to be used later on next-subscribe

---

src/js/server/components/ConsentLite.tsx

Add the possibility to customize terms and conditions message and hide the footer for consent lite component.
This is aim to cover some requirements needed for this ticket https://financialtimes.atlassian.net/browse/ACQ-972

ACQ-1007: customize consent lite component for in article sign-in feature

---

src/js/server/components/ConsentLite.tsx

Updating wording for consent lite component moreinfo field. Following designer recommendations  [here](https://financialtimes.slack.com/archives/C024DRXH65A/p1624964141000800?thread_ts=1624909422.002300&cid=C024DRXH65A).
Ticket https://financialtimes.atlassian.net/browse/ACQ-1007

ACQ-1007: update copy for moreinfo field on consent lite component

---

Makefile
main.scss
package-lock.json
package.json
src/js/client/message.ts
src/js/client/reconsent.ts
src/scss/common.scss
src/scss/components/alert-message.scss
src/scss/reconsent.scss
test/client/live-consent.spec.ts
test/unit/helpers.spec.ts
webpack.config.js

[ADSDEV-1052](https://financialtimes.atlassian.net/browse/ADSDEV-1052)
* Install Origami components imported in `.scss` files via npm.
* Update the `@import` path from `@import 'o-xyz'` to `@import '@financial-times/o-xyz'` to successfully find the origami dependency in the node_modules directory.
* Use webpack to compile the `.scss` files using the same plugin used in page kit apps `PageKitSassPlugin` like `next-control-centre`.
* Check if the `.scss` files can be compiled as part of the CircleCI `test` job.

ADSDEV-1052 install origami components via npm

---

templates/banner.html
templates/components/changes-saved-message.html
templates/components/error-message-core.html
templates/components/fow-hidden-inputs.html
templates/components/overlay.html
templates/components/yes-no-switch.html
templates/confirmation.html
templates/consent.html
templates/settings.html
templates/subheading.html

* Handlebars templates were removed in [v13 Handlebars to JSX](https://github.com/Financial-Times/n-profile-ui/releases/tag/v13.0.2) - see related PR https://github.com/Financial-Times/n-profile-ui/pull/71.
* A few active repositories have not migrated yet to v13, and are still using the handlebars templates from n-profile-ui < v12, including `next-control-centre`.
* We have to release a new major version of `n-profile-ui` where all the Origami bower components have been removed and replaced by their equivalent npm version.
Restores the handlebars templates which have been removed in v13 and are still needed in `next-control-centre` and a few other active repos.

ADSDEV-1052 restore handlebars templates

---

src/js/server/components/Consent.tsx
src/scss/form.scss
templates/consent.html

One example where the label is using the 80% of width under `Top stories and featuress`
With this change it will be using 100% width

ACQ 1472 Full width to the consent label

---

package.json

Jira: [ADSDEV-1052](https://financialtimes.atlassian.net/browse/ADSDEV-1052)
`n-profile-ui` installs the `n-internal-tool` via `package.json`.
`n-internal-tools` uses an old version Origami build string, and it's also not required anymore by `n-profile-ui`; the dependency was previously used to spin up the demos.
Therefore, we can uninstall `n-internal-tool` from `n-profile-ui`.

ADSDEV-1052 Remove unused n-internal-tool dependency

---

src/js/server/components/Consent.tsx

Add ID and ARIA tags to labels and input. This will help us to solve 2 purposes one easy-to-get E2E test by having unique IDs and making interactive elements more accessible.
Ticket: https://financialtimes.atlassian.net/browse/ACQ-1658

Add ID and ARIA tags to labels and input

---

.circleci/config.yml

Migrate CI nightly workflow from a scheduled workflow to a scheduled pipeline.
I followed the CircleCI guide [Migrate schedule workflows](https://circleci.com/docs/scheduled-pipelines#migrate-scheduled-workflows).
I tested the new scheduled pipeline by creating a new trigger called [Nightly trigger](https://app.circleci.com/settings/project/github/Financial-Times/n-profile-ui/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2FFinancial-Times%2Fn-profile-ui&success=true).
The nightly workflow has been subsequently kicked off https://app.circleci.com/pipelines/github/Financial-Times/n-profile-ui/1186/workflows/e1d54d07-c4df-41ae-8f06-386587951419
I've subsequently configured again the Nightly trigger to execute the workflow at every day at midnight.

ADSDEV-1111: CI nightly: migrate scheduled workflow to scheduled pipeline

---

src/js/server/components/ConsentLite.tsx
src/js/types/fow-api.d.ts

We have a google extended meter feature where we ask users to read more content via google, during this flow we ask the user to update consent preferences. We want to use the existing consent record which is 'consentB2CSignup' but with different variations in the footer for the google consent page.
Footer with the right message:

ACQ 1972: Consent Lite Footer  

---

package-lock.json
package.json

Re. this PR comment: https://github.com/Financial-Times/next-newsletter-signup/pull/360#discussion_r1113327947
Creating a release with this change will allow next-newsletter-signup to include the requisite version of n-logger in its dependency tree.
The only breaking changes in [n-mask-logger v7](https://github.com/Financial-Times/n-mask-logger/releases/tag/v7.0.0) are dropped support for Node v12 and npm 6.
I will release this change as a patch.

Upgrade @financial-times/n-user-api-client 4.1.0 -> 4.1.1

---

package-lock.json
package.json

The latest version of this module was preventing next-control-centre from being able to start because of a missing dependency. This was fixed in n-user-api-client and we need to also bump it here.
Helps resolve [CPREL-518](https://financialtimes.atlassian.net/browse/CPREL-518)
[CPREL-518]: https://financialtimes.atlassian.net/browse/CPREL-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump n-user-api-client to include Joi

---

src/js/helpers.ts
src/js/server/components/Consent.tsx
src/js/server/components/ConsentLite.tsx
src/js/server/components/Overlay.tsx
src/js/server/components/ToggleSwitch.tsx
src/js/types/helpers.d.ts
test/unit/helpers.spec.ts

Some time ago, consent components (`Consent` and `ConsentLite`) had been modified to move from html `radio-button` to `checkbox` input fields.
If a checkbox is unchecked when its form is submitted, neither the name nor the value is submitted to the server.
Currently, all repos using `Consent` and `ConsentLite` are not receiving the "no" value when they are unchecked. That means that the unchecked consents are not sent through the Consent API and then FT doesn't know if the consents were presented to the user (only the checked consents are sent today).
In addition, when all consents in the page are unchecked, then the server is throwing an error when calling [buildConsentRecord](https://github.com/Financial-Times/n-profile-ui/blob/v14.1.2/src/js/helpers.ts#LL126C17-L126C35) method because …

ACQ-2216: adding default "no" value to Consent & ConsentLite input checkbox fields

---

src/js/client/consent.ts
src/js/client/update-on-save.ts
test/client/update-on-save.spec.ts

There is an error on client side when landing on /buy/offer/{offerId}/preferences page that prevents attach to the tracking context (later sent to spoor API) the consents shown to the user.
The code is using a n-profile-ui helper function that is still trying to get radio buttons instead of checkboxes.
https://financialtimes.atlassian.net/browse/ACQ-2273

ACQ-2273: Errors when trying to add the consents shown to the user into the tracking context

---

package-lock.json
package.json
test/client/helpers/polyfills.ts

This replaces n-logger usage with Reliability Kit logger. It's a breaking change because the module now logs to `stdout` rather than sending logs directly to Splunk. This should be a safe upgrade for most Customer Products apps.

Breaking: replace n-logger with Reliability Kit logger

---

package.json

This PR ensures that `dist/`, `templates/`, `main.scss` and `src/scss/` are included in the published module
This beta release demonstrates the expected behaviour:
https://www.npmjs.com/package/@financial-times/n-profile-ui/v/17.1.5-beta.3?activeTab=code
Once accepted we can cut a v17.1.5 release (required by `next-control-centre`)

ADSDEV-1700: Ensure correct assets are published

---

src/js/server/components/ConsentLite.tsx

We (acquisition team) are working on the new feature of in-article sign up for US Newsletter. Consent box wording for this signup experience needs to be changed. 
Highlighted line needs to be removed as we will only be signing use up for US election newsletter and not the Editor's Digest one.
https://financialtimes.atlassian.net/browse/ACQ-2702
I have added `inArticleSignUpUSElection` in the custom info to handle this case. 
`next-subscribe` PR - https://github.com/Financial-Times/next-subscribe/pull/2864

Consent change for US election sign up
